name: Fetch OHLCV from Kraken
on:
  schedule:
    - cron: '5 23 * * *'   # tutti i giorni 23:05 UTC
  workflow_dispatch:       # esecuzione manuale
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python fetch_ohlcv.py
      - name: Commit & push
        run: |
          git config user.name  "data-bot"
          git config user.email "data-bot@users.noreply.github.com"
          git add -A
          git commit -m "data: update $(date -u +'%Y-%m-%d')" || echo "no changes"
          git push
