name: Crypto Daily Data & Simulation

on:
  schedule:
    - cron: "05 06 * * 1-5"   # 06:05 UTC lun-ven
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: crypto-daily
  cancel-in-progress: false

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas python-dateutil requests ccxt

      - name: Fetch prices & simulate
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/fetch_and_simulate.py

      - name: Build per-asset time series CSVs
        run: |
          python scripts/build_timeseries.py

      - name: Apply pending orders (slippage & fees)
        env:
          SLIPPAGE_BPS: "25"   # 0.25% slippage
          FEE_BPS: "10"        # 0.10% fee
        run: |
          python scripts/simulator.py || true

      - name: Fetch OHLC (CoinGecko)
        env:
          OHLC_DAYS: "365"        # storico da mantenere
          OHLC_SLEEP_S: "1.2"     # rate limit
          OHLC_MAX_COINS: "0"     # 0 = tutte le coin dello snapshot
        run: |
          python scripts/fetch_ohlc.py
          
            - name: Commit & rebase-safe push
        env:
          BRANCH: ${{ github.ref_name }}   # es. main
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add data/ portfolio/
          git commit -m "Daily update: data, sim, fills & NAV: $(date -u +'%Y-%m-%d')" || echo "Nothing to commit"

          # Allineati al remoto e rebase delle tue commit sopra
          git fetch origin "$BRANCH"
          # Se ci sono conflitti sui file generati, di solito vogliamo TENERE la versione del job
          # Attiva il backend 'merge' per usare -X ours
          git config rebase.backend merge
          git rebase -X ours "origin/$BRANCH" || (git rebase --abort && exit 1)

          # Push sul branch
          git push origin HEAD:"$BRANCH"

